spring:

  # Часть настроек ниже написана через '.', поскольку какие-то настройки это нативные свойства Kafka, которые передаются в Kafka и в её документации они описаны через '.'.
  # Какие-то являются настройками spring-kafka (например, spring.json.trusted.packages) где также выбрали dot.notation стратегию именования.
  # Если написать, например, max-poll-records, то настройка тоже должна сработать, но лишь потому что Spring Boot сам заменит '-' на '.'
  # Другие же настройки относятся к spring-boot и там уже принят kebab-case. Например, group-id, т.к. это не свойство передаваемое в кафку напрямую.
  # Это настройка Spring-boot.
  kafka:
    consumer:
      group-id: springBootAppGroupId
      auto-offset-reset: earliest
      properties:
        max.poll.records: 20
        spring.json.trusted.packages: com.barabanov
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

kafka-topics:
  simple-msg-topic-name: SIMPLE_MSG_TOPIC
  simple-msg-topic-concurrency: 1