kafka:
  topic.name: springBootTopic
  groupId: springBootConsumer


spring:
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json:
          trusted.packages: com.barabanov
          value.default.type: 'com.barabanov.Cart'

      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 100
