spring:
  kafka:
    producer:
      properties:
        spring.json.add.type.headers: false

    consumer:
      properties:
        spring.json:
          trusted.packages: com.barabanov
          value.default.type: 'com.barabanov.Cart'